dist: xenial
language: python
os: linux
env:
  global:
    - DEVPI_INDEX="devpi-travis/${TRAVIS_REPO_SLUG/\//_}_${TRAVIS_BRANCH/\//_}"
install: travis_retry pip install tox tox-travis devpi-client
script:
  - export DEVPI_INDEX_URL="https://pypi.org/simple/"
  - test "${DEVPI_TRAVIS_PASSWD}" != "" && export DEVPI_INDEX_URL="https://m.devpi.net/${DEVPI_INDEX}/+simple/" || true
  - echo "${DEVPI_INDEX_URL}"
  - cd $PROJECT
  - travis_retry tox -i "${DEVPI_INDEX_URL}" --pre -- -v
stages:
  - name: create packages
    if: type IN (push, api, cron)
  - test
jobs:
  include:
    - stage: create packages
      addons: []
      install: travis_retry pip install tox devpi-client towncrier
      python: "3.6"
      env: []
      script:
        - devpi use https://m.devpi.net/devpi-travis
        - devpi login devpi-travis --password ${DEVPI_TRAVIS_PASSWD}
        - python .ci/cleanup_devpi_indices.py
        - yes yes | devpi index --delete "${DEVPI_INDEX}" || true
        - devpi index -c "${DEVPI_INDEX}" bases=root/pypi
        - devpi use "${DEVPI_INDEX}"
        - devpi push --index root/pypi devpi-server==4.0.0 "${DEVPI_INDEX}"
        - devpi push --index root/pypi devpi-server==5.2.0 "${DEVPI_INDEX}"
        - cd ${TRAVIS_BUILD_DIR}/common
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/server
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/web
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/client
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/postgresql
        - yes | towncrier
        - devpi upload

    #########################
    #
    # common
    #
    #########################

    - stage: test
      python: "2.7"
      env: PROJECT=common

    - stage: test
      python: "pypy2.7-7.1.1"
      env: PROJECT=common

    - stage: test
      python: "3.4"
      env: PROJECT=common

    - stage: test
      python: "3.7"
      env: PROJECT=common

    - stage: test
      python: "nightly"
      env: PROJECT=common

    - stage: test
      python: "pypy3.6-7.1.1"
      env: PROJECT=common

    #########################
    #
    # server
    #
    #########################

    - stage: test
      python: "3.4"
      env: PROJECT=server

    - stage: test
      python: "3.7"
      env: PROJECT=server

    - stage: test
      python: "nightly"
      env: PROJECT=server

    - stage: test
      python: "pypy3.6-7.1.1"
      env: PROJECT=server

    #########################
    #
    # web
    #
    #########################

    - stage: test
      python: "3.4"
      env: PROJECT=web

    - stage: test
      python: "3.7"
      env: PROJECT=web

    - stage: test
      python: "nightly"
      env: PROJECT=web

    - stage: test
      python: "pypy3.6-7.1.1"
      env: PROJECT=web

    #########################
    #
    # client
    #
    #########################

    - stage: test
      python: "2.7"
      env: PROJECT=client

    - stage: test
      python: "pypy2.7-7.1.1"
      env: PROJECT=client

    - stage: test
      python: "3.4"
      env: PROJECT=client

    - stage: test
      python: "3.7"
      env: PROJECT=client

    - stage: test
      python: "nightly"
      env: PROJECT=client

    - stage: test
      python: "pypy3.6-7.1.1"
      env: PROJECT=client

    #########################
    #
    # postgresql
    #
    #########################

    - stage: test
      python: "3.5"
      env: PROJECT=postgresql
      addons:
        apt:
          packages:
            - nginx
        postgresql: "9.5"

    - stage: test
      python: "pypy3.6-7.1.1"
      env: PROJECT=postgresql
      addons:
        apt:
          packages:
            - nginx
        postgresql: "9.5"

  allow_failures:
    - stage: test
      python: "nightly"
      env: PROJECT=client

    - stage: test
      python: "nightly"
      env: PROJECT=web
