language: python
sudo: false
addons:
  postgresql: "9.4"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"
env:
  global:
    - DEVPI_INDEX="devpi-travis/${TRAVIS_REPO_SLUG/\//_}_${TRAVIS_BRANCH/\//_}"
  matrix:
    - PROJECT=common
    - PROJECT=server
    - PROJECT=web
    - PROJECT=client
    - PROJECT=postgresql
install: pip install tox-travis devpi-client
script:
  - export DEVPI_INDEX_URL="https://pypi.python.org/simple/"
  - test "${DEVPI_TRAVIS_PASSWD}" != "" && export DEVPI_INDEX_URL="https://devpi.net/${DEVPI_INDEX}"
  - echo "${DEVPI_INDEX_URL}"
  - cd $PROJECT
  - tox -i "${DEVPI_INDEX_URL}" --pre
stages:
  - name: create packages
    if: type IN (push, api, cron)
  - test
jobs:
  include:
    - stage: create packages
      addons: []
      install: pip install devpi-client towncrier
      python: "2.7"
      env: []
      script:
        - devpi use https://devpi.net/devpi-travis
        - devpi login devpi-travis --password ${DEVPI_TRAVIS_PASSWD}
        - yes yes | devpi index --delete "${DEVPI_INDEX}" || true
        - devpi index -c "${DEVPI_INDEX}" bases=root/pypi
        - devpi use "${DEVPI_INDEX}"
        - devpi push --index root/pypi devpi-server==4.0.0 "${DEVPI_INDEX}"
        - devpi push --index root/pypi devpi-server==4.2.1 "${DEVPI_INDEX}"
        - cd ${TRAVIS_BUILD_DIR}/common
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/server
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/web
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/client
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/postgresql
        - yes | towncrier
        - devpi upload
