exclude = [
    "doc/",
]

target-version = "py37"


[format]
exclude = [
    "client/devpi/__main__.py",
    "client/devpi/getjson.py",
    "client/devpi/hookspecs.py",
    "client/devpi/index.py",
    "client/devpi/install.py",
    "client/devpi/list_remove.py",
    "client/devpi/login.py",
    "client/devpi/main.py",
    "client/devpi/push.py",
    "client/devpi/pypirc.py",
    "client/devpi/refresh.py",
    "client/devpi/use.py",
    "client/devpi/user.py",
    "client/testing/conftest.py",
    "client/testing/functional.py",
    "client/testing/reqmock.py",
    "client/testing/simpypi.py",
    "client/testing/test_functional.py",
    "client/testing/test_index.py",
    "client/testing/test_install.py",
    "client/testing/test_list_remove.py",
    "client/testing/test_login.py",
    "client/testing/test_main.py",
    "client/testing/test_push.py",
    "client/testing/test_pypirc.py",
    "client/testing/test_test.py",
    "client/testing/test_upload.py",
    "client/testing/test_use.py",
    "client/testing/test_user.py",
    "debugging/devpi_debugging/main.py",
    "debugging/devpi_debugging/views.py",
    "postgresql/devpi_postgresql/main.py",
    "postgresql/pytest_devpi_postgresql/__init__.py",
    "postgresql/setup.py",
    "server/devpi_server/auth.py",
    "server/devpi_server/auth_basic.py",
    "server/devpi_server/auth_devpi.py",
    "server/devpi_server/config.py",
    "server/devpi_server/exceptions.py",
    "server/devpi_server/filestore.py",
    "server/devpi_server/filestore_fs.py",
    "server/devpi_server/fileutil.py",
    "server/devpi_server/fsck.py",
    "server/devpi_server/genconfig.py",
    "server/devpi_server/hookspecs.py",
    "server/devpi_server/importexport.py",
    "server/devpi_server/init.py",
    "server/devpi_server/interfaces.py",
    "server/devpi_server/keyfs.py",
    "server/devpi_server/keyfs_sqlite.py",
    "server/devpi_server/keyfs_sqlite_fs.py",
    "server/devpi_server/keyfs_types.py",
    "server/devpi_server/log.py",
    "server/devpi_server/main.py",
    "server/devpi_server/markers.py",
    "server/devpi_server/middleware.py",
    "server/devpi_server/mirror.py",
    "server/devpi_server/model.py",
    "server/devpi_server/mythread.py",
    "server/devpi_server/passwd.py",
    "server/devpi_server/readonly.py",
    "server/devpi_server/replica.py",
    "server/devpi_server/sizeof.py",
    "server/devpi_server/vendor/_pip.py",
    "server/devpi_server/view_auth.py",
    "server/devpi_server/views.py",
    "server/pytest_devpi_server/__init__.py",
    "server/setup.py",
    "server/test_devpi_server/conftest.py",
    "server/test_devpi_server/example.py",
    "server/test_devpi_server/functional.py",
    "server/test_devpi_server/plugin.py",
    "server/test_devpi_server/reqmock.py",
    "server/test_devpi_server/simpypi.py",
    "server/test_devpi_server/test_auth.py",
    "server/test_devpi_server/test_authcheck.py",
    "server/test_devpi_server/test_config.py",
    "server/test_devpi_server/test_conftest.py",
    "server/test_devpi_server/test_filestore.py",
    "server/test_devpi_server/test_fileutil.py",
    "server/test_devpi_server/test_fsck.py",
    "server/test_devpi_server/test_genconfig.py",
    "server/test_devpi_server/test_importexport.py",
    "server/test_devpi_server/test_keyfs.py",
    "server/test_devpi_server/test_keyfs_sqlite_fs.py",
    "server/test_devpi_server/test_log.py",
    "server/test_devpi_server/test_main.py",
    "server/test_devpi_server/test_mirror.py",
    "server/test_devpi_server/test_mirror_no_project_list.py",
    "server/test_devpi_server/test_model.py",
    "server/test_devpi_server/test_mythread.py",
    "server/test_devpi_server/test_nginx.py",
    "server/test_devpi_server/test_nginx_replica.py",
    "server/test_devpi_server/test_permissions.py",
    "server/test_devpi_server/test_replica.py",
    "server/test_devpi_server/test_replica_functional.py",
    "server/test_devpi_server/test_reqmock.py",
    "server/test_devpi_server/test_stage_customizer.py",
    "server/test_devpi_server/test_streaming.py",
    "server/test_devpi_server/test_streaming_nginx.py",
    "server/test_devpi_server/test_streaming_replica.py",
    "server/test_devpi_server/test_streaming_replica_nginx.py",
    "server/test_devpi_server/test_view_auth.py",
    "server/test_devpi_server/test_views.py",
    "server/test_devpi_server/test_views_patch.py",
    "server/test_devpi_server/test_views_push_external.py",
    "server/test_devpi_server/test_views_status.py",
    "web/devpi_web/clear_index.py",
    "web/devpi_web/compat.py",
    "web/devpi_web/config.py",
    "web/devpi_web/description.py",
    "web/devpi_web/doczip.py",
    "web/devpi_web/hookspecs.py",
    "web/devpi_web/indexing.py",
    "web/devpi_web/main.py",
    "web/devpi_web/null_index.py",
    "web/devpi_web/views.py",
    "web/devpi_web/whoosh_index.py",
    "web/setup.py",
    "web/tests/conftest.py",
    "web/tests/test_indexing.py",
    "web/tests/test_main.py",
    "web/tests/test_theme.py",
    "web/tests/test_views.py",
    "web/tests/test_views_docs.py",
    "web/tests/test_views_misc.py",
    "web/tests/test_views_search.py",
    "web/tests/test_views_toxresults.py",
    "web/tests/test_whoosh_index.py",
]


[lint]
select = ["ALL"]
ignore = [
    "A003", # ignore - class attribute name shadows builtin
    "ANN", # maybe cleanup later - annotations
    "C408", # ignore - dict call
    "C901", # ignore - complex structure
    "D", # ignore - docstrings
    "E501", # ignore - line too long
    "E741", # ignore - ambiguous variable name
    "EM101", # ignore - string literal in exception
    "EM102", # ignore - f-string in exception
    "N", # ignore - naming
    "PERF203", # ignore (false positive?) - try-except in loop
    "PLR0913", # ignore - too many arguments
    "PLR0915", # maybe cleanup later
    "PLR2004", # ignore - magic value comparison
    "PT001", # ignore - pytest.fixture
    "PT023", # ignore - pytest.mark.nomocking
    "PTH", # ignore - pathlib
    "Q", # ignore - quotes style
    "S101", # ignore - asserts
    "SLF001", # ignore - private member accessed
    "TD", # ignore - todos
    "TRY003", # ignore - raise vanilla args
    "UP031", # maybe cleanup later - printf string formatting
]

pyupgrade.keep-runtime-typing = true


[lint.isort]
case-sensitive = true
force-single-line = true
from-first = true
lines-after-imports = 2
no-sections = true
order-by-type = false


[lint.per-file-ignores]
".ci/cleanup_devpi_indices.py" = [
    "INP001", # ignore - implicit namespace package
    "S603", # ignore - subprocess untrusted input
    "S607", # ignore - subprocess partial executable path
    "T201", # ignore - print found
]
".ci/ruff-format-diff.py" = [
    "COM812", # ignore - ruff format
]
"client/devpi/hookspecs.py" = [
    "ARG001", # unused function argument on hookspecs https://github.com/astral-sh/ruff/issues/9803
]
"client/testing/conftest.py" = [
    "INP001", # ignore - implicit namespace package
    "S603", # ignore - subprocess untrusted input
    "T201", # ignore - print found
]
"server/devpi_server/hookspecs.py" = [
    "ARG001", # unused function argument on hookspecs https://github.com/astral-sh/ruff/issues/9803
]
"server/test_devpi_server/plugin.py" = [
    "S603", # ignore - subprocess untrusted input
    "T201", # ignore - print found
]
"web/devpi_web/hookspecs.py" = [
    "ARG001", # unused function argument on hookspecs https://github.com/astral-sh/ruff/issues/9803
]
"web/tests/conftest.py" = [
    "INP001", # ignore - implicit namespace package
]
"*/pytest_devpi_postgresql/__init__.py" = [
    "S603", # ignore - subprocess untrusted input
    "S607", # ignore - subprocess partial executable path
]
"setup.py" = [
    "INP001", # ignore - implicit namespace package
    "SIM905", # cleanup later
]
"test_*" = [
    "INP001", # ignore - implicit namespace package
    "S105", # ignore - possible hardcoded password
    "S106", # ignore - possible hardcoded password
    "S113", # ignore - requests call without timeout
    "S324", # ignore - md5 - use usedforsecurity=False with Python 3.9
    "S603", # ignore - subprocess untrusted input
    "S607", # ignore - subprocess partial executable path
    "T201", # ignore - print found
]
