---
name: "Documentation"

on: workflow_dispatch

jobs:
  documentation:
    name: "Create documentation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          persist-credentials: false
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel --group dev -e common -e client -e postgresql -e server -e web
      - name: "Regen documentation"
        run: |
          set -xe -o nounset
          export DEVPI_INDEXNAME="devpi-github/docs"
          export PIP_INDEX_URL="https://pypi.org/simple/"
          export PYTHONWARNINGS=ignore
          devpi use https://m.devpi.net/devpi-github
          devpi login devpi-github --password ${{ secrets.DEVPI_GITHUB_PASSWORD }}
          .ci/upload-packages.sh
          mkdir .temp
          export TMPDIR=$(pwd)/.temp/
          pushd doc
          make regen
          popd
      - name: "Build documentation"
        run: |
          pushd doc
          make doczip
          popd
      - name: "Upload documentation"
        run: |
          pushd doc
          devpi upload *.doc.zip
          popd
      - name: "Diff documentation"
        run: |
          git diff --exit-code || echo "::warning::The generated documentation has differences"
